apiVersion: v1
kind: service
metadata:
   name: myjavaapp-svc
   labels:
    app: myjavaapp
    version: 2.60.2
spec:
  type: Nodeport
  ports: 
  - port: 8080
    nodeport: 30001
    protocol: TCP 
  selector: 
    app: myjavaapp
    version: 2.60.2